defaults: &defaults
  docker:
    - image: nerveshub/docker-build:alpine-3.8
  working_directory: ~/repo

remote_docker: &remote_docker
  setup_remote_docker:
    version: 17.09.0-ce

docker_env: &docker_env
  run:
    name: Set docker env
    command: |
      if [ -z "$CIRCLE_TAG" ]; then
      BRANCH=$(git rev-parse --abbrev-ref HEAD)
        SHA=$(git rev-parse --short HEAD)
        TAG=$(echo "v.$BRANCH.$SHA" | sed 's/\//_/g')
      else
        TAG=$CIRCLE_TAG
      fi
      echo "export DOCKER_TAG=$TAG" >> $BASH_ENV
      echo "export DOCKER_IMAGE=nerveshub/$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV

docker_build_test: &docker_build_test
  run:
    name: Build docker image
    command: |
      docker build \
        -t $DOCKER_IMAGE:$DOCKER_TAG .

docker_build_release: &docker_build_release
  run:
    name: Build docker image
    command: |
      docker build \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -f rel/Dockerfile.build .

docker_run_test: &docker_run_test
  run: 
    name: Run the tests
    command: |
      docker run \
        $DOCKER_IMAGE:$DOCKER_TAG \
        mix test

docker_check_formatting: &docker_check_formatting
  run: 
    name: Check formatting
    command: |
      docker run \
        $DOCKER_IMAGE:$DOCKER_TAG \
        mix format --check-formatted

docker_save: &docker_save
  run:
    name: Save docker images
    command: |
      mkdir -p /docker
      docker save \
        nerveshub/$APP_NAME:$DOCKER_TAG \
        -o /docker/$APP_NAME-$DOCKER_TAG.tar

docker_import: &docker_import
  run:
    name: Import docker images
    command: |
      docker load \
        -i /docker/$APP_NAME-$DOCKER_TAG.tar

docker_push: &docker_push
  run: 
    name: Push docker image to dockerhub
    command: |
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      docker push \
        $DOCKER_IMAGE:$DOCKER_TAG

deploy: &deploy
  run:
    name: Deploy to production
    command: |
      ecs-deploy \
        -c nerves-hub \
        -n nerves-hub-ca \
        -i nerveshub/nerves_hub_ca:$DOCKER_TAG \
        -t 600 \
        --enable-rollback \
        --max-definitions 10

send_notifications: &send_notifications
  run: 
    name: Send notifications
    command: |
      rel/scripts/slack-notification.sh \
        $SLACK_INCOMING_WEBHOOK_URL \
        "#nerves-hub" \
        "NervesHub Deployment" "Deployed Image: \`$DOCKER_IMAGE:$DOCKER_TAG\`"

version: 2
jobs:
  test:
    <<: *defaults
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - <<: *remote_docker
      - run: echo "export APP_NAME=nerves_hub_ca" >> $BASH_ENV
      - <<: *docker_env
      - <<: *docker_build_test
      - <<: *docker_run_test
      - <<: *docker_check_formatting

  build:
    <<: *defaults
    environment:
      MIX_ENV: prod
    steps:
      - checkout
      - <<: *remote_docker
      - run: echo "export APP_NAME=nerves_hub_ca" >> $BASH_ENV
      - <<: *docker_env
      - <<: *docker_build_release
      - <<: *docker_save
      - save_cache:
          key: docker-{{ .Branch }}-{{ .Revision }}
          paths: "/docker"

  deploy:
    <<: *defaults
    steps:
      - checkout
      - <<: *remote_docker
      - run: echo "export APP_NAME=nerves_hub_ca" >> $BASH_ENV
      - <<: *docker_env
      - restore_cache:
          keys:
            - docker-{{ .Branch }}-{{ .Revision }}
      - <<: *docker_import
      - <<: *docker_push
      - <<: *deploy
      - <<: *send_notifications

workflows:
  version: 2
  pipeline:
      jobs:
        - test
        - build:
            context: org-global
            requires:
              - test
        - deploy:
            context: org-global
            requires:
              - build
            filters:
              branches:
                only: master
